//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorReason {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorReason() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computer.Properties.Resources.ErrorReason", typeof(ErrorReason).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key -- Key Data Corruptted.
        /// </summary>
        internal static string CorruptedKey {
            get {
                return ResourceManager.GetString("CorruptedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key -- Driver Missing.
        /// </summary>
        internal static string DriverMissing {
            get {
                return ResourceManager.GetString("DriverMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available -- New Version Available.
        /// </summary>
        internal static string DriverOutdated {
            get {
                return ResourceManager.GetString("DriverOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key --Extension Not Used.
        /// </summary>
        internal static string ExtensionMissing {
            get {
                return ResourceManager.GetString("ExtensionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key -- Recent Document Listing.
        /// </summary>
        internal static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key -- Shared Library Missing.
        /// </summary>
        internal static string InvalidLibrary {
            get {
                return ResourceManager.GetString("InvalidLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key -- Shortcut Target Missing.
        /// </summary>
        internal static string ShortcutMissing {
            get {
                return ResourceManager.GetString("ShortcutMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key -- Invalid Startup File.
        /// </summary>
        internal static string StartupMissing {
            get {
                return ResourceManager.GetString("StartupMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key -- Extension Not Used.
        /// </summary>
        internal static string UnusedExtension {
            get {
                return ResourceManager.GetString("UnusedExtension", resourceCulture);
            }
        }
    }
}
