//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegistryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computer.Properties.Resources.RegistryStrings", typeof(RegistryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalProductId.
        /// </summary>
        internal static string BinaryKey {
            get {
                return ResourceManager.GetString("BinaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\Windows\\ShellNoRoam\\MUICache.
        /// </summary>
        internal static string CacheRegistryBase {
            get {
                return ResourceManager.GetString("CacheRegistryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Drivers32.
        /// </summary>
        internal static string DriversRegistryBase {
            get {
                return ResourceManager.GetString("DriversRegistryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1.
        /// </summary>
        internal static string LocalhostIPAddress {
            get {
                return ResourceManager.GetString("LocalhostIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Wow6432Node\\Microsoft\\MSDN\\8.0\\Registration.
        /// </summary>
        internal static string MicrosoftOffice2010 {
            get {
                return ResourceManager.GetString("MicrosoftOffice2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastProduct.
        /// </summary>
        internal static string Office2010Build {
            get {
                return ResourceManager.GetString("Office2010Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIDKey.
        /// </summary>
        internal static string Office2010ProductId {
            get {
                return ResourceManager.GetString("Office2010ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId.
        /// </summary>
        internal static string Office2010ProductKey {
            get {
                return ResourceManager.GetString("Office2010ProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Wow6432Node\\Microsoft\\Office\\14.0\\Common\\ProductVersion.
        /// </summary>
        internal static string Office2010Version {
            get {
                return ResourceManager.GetString("Office2010Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string OfficeRegisteredTo {
            get {
                return ResourceManager.GetString("OfficeRegisteredTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessorNameString.
        /// </summary>
        internal static string ProcessorNameKey {
            get {
                return ResourceManager.GetString("ProcessorNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARDWARE\\DESCRIPTION\\System\\CentralProcessor\\0.
        /// </summary>
        internal static string ProcessorRegistryBase {
            get {
                return ResourceManager.GetString("ProcessorRegistryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VendorIdentifier.
        /// </summary>
        internal static string ProcessorVendorKey {
            get {
                return ResourceManager.GetString("ProcessorVendorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId.
        /// </summary>
        internal static string ProductIdent {
            get {
                return ResourceManager.GetString("ProductIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductName.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Explorer\\RecentDocs.
        /// </summary>
        internal static string RecentDocsRegistryBase {
            get {
                return ResourceManager.GetString("RecentDocsRegistryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisteredOwner.
        /// </summary>
        internal static string RegisteredTo {
            get {
                return ResourceManager.GetString("RegisteredTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\SharedDLLs.
        /// </summary>
        internal static string SharedLibrariesRegistryBase {
            get {
                return ResourceManager.GetString("SharedLibrariesRegistryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\\CurrentControlSet\\Enum\\USBSTOR.
        /// </summary>
        internal static string USBRegistryBase {
            get {
                return ResourceManager.GetString("USBRegistryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentVersion.
        /// </summary>
        internal static string VersionBase {
            get {
                return ResourceManager.GetString("VersionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentBuild.
        /// </summary>
        internal static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion.
        /// </summary>
        internal static string WindowsRegistryBase {
            get {
                return ResourceManager.GetString("WindowsRegistryBase", resourceCulture);
            }
        }
    }
}
