//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scanners {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scanners() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computer.Properties.Resources.Scanners", typeof(Scanners).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveX/Com Scanner.
        /// </summary>
        internal static string ActiveXComScanner {
            get {
                return ResourceManager.GetString("ActiveXComScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Scanner.
        /// </summary>
        internal static string ExtensionScanner {
            get {
                return ResourceManager.GetString("ExtensionScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Font Scanner.
        /// </summary>
        internal static string FontScanner {
            get {
                return ResourceManager.GetString("FontScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Files Scanner.
        /// </summary>
        internal static string HelpFileScanner {
            get {
                return ResourceManager.GetString("HelpFileScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Scanner.
        /// </summary>
        internal static string InvalidDriverScanner {
            get {
                return ResourceManager.GetString("InvalidDriverScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Scanner.
        /// </summary>
        internal static string OpenPortScanner {
            get {
                return ResourceManager.GetString("OpenPortScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Document Scanner.
        /// </summary>
        internal static string RecentDocumentScanner {
            get {
                return ResourceManager.GetString("RecentDocumentScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Libraries Scanner.
        /// </summary>
        internal static string SharedLibrariesScanner {
            get {
                return ResourceManager.GetString("SharedLibrariesScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Scanner.
        /// </summary>
        internal static string ShortcutScanner {
            get {
                return ResourceManager.GetString("ShortcutScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Settings Scanner.
        /// </summary>
        internal static string SoftwareSettingsScanner {
            get {
                return ResourceManager.GetString("SoftwareSettingsScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Event Scanner.
        /// </summary>
        internal static string SoundEventScanner {
            get {
                return ResourceManager.GetString("SoundEventScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Scanner.
        /// </summary>
        internal static string StartupScanner {
            get {
                return ResourceManager.GetString("StartupScanner", resourceCulture);
            }
        }
    }
}
